# lightning.pytorch==2.4.0
seed_everything: true
trainer:
  callbacks:
    class_path: PredictionWriter
    init_args:
      output_dir: 'predictions'
  logger: false
  accelerator: 'mps'
  enable_progress_bar: true
  enable_model_summary: true
  inference_mode: true
model:
  net:
    class_path: segmentation_models_pytorch.Unet
    init_args:
      encoder_name: 'resnet34'
      encoder_weights: null
      in_channels: 3
      decoder_use_batchnorm: true
      decoder_attention_type: 'scse'
      classes: 1
  criterion:
    class_path: segmentation_models_pytorch.losses.JaccardLoss
    init_args:
      mode: 'binary'
      from_logits: true
data:
  data_dir: data/leaf_veins/
  batch_size: 1
  num_workers: 4
return_predictions: false
ckpt_path: "lightning_logs/lightning_logs/version_2/checkpoints/epoch=2-step=9.ckpt"
